Add NEP Organization to NCR Silver Auth
cyclr/docs pull request #392
Opened 2022-12-01 16:20 UTC by Frouget

2022-12-01 16:30 UTC, developingharry commented on pages/connector-authentication/NCRSilver-Authentication.md
> +4.  **NEP Organization** is located under Service User Name. It is the value after "acct:" and before the "@" symbol.
4.  **NEP Organization** is located under Service User Name. It is the value after "acct:" and before the "@" symbol.  

If the Service User Name is acct:**test-drive-399bcc60-9426-4e46-bf9c-76f3e6e5883e**@44423c74-6324-446b-97d2-e88538c3c926 for example, the **NEP Organization** you need is **test-drive-399bcc60-9426-4e46-bf9c-76f3e6e5883e**.

2022-12-01 16:31 UTC, developingharry commented on pages/connector-authentication/NCRSilver-Authentication.md
> +4.  **NEP Organization** is located under Service User Name. It is the value after "acct:" and before the "@" symbol.
Something like that?  Maybe formatted a bit better (the review editor is a bit naff).

Feel like there should be an example anyway.

2022-12-01 16:31 UTC, developingharry requested changes
See notes :)

2022-12-05 12:19 UTC, erin-lw commented on pages/connector-authentication/NCRSilver-Authentication.md
> +You need a **Shared Key** and **Secret Key** in order to access the connector. You will also need a **NEP Organization** value.
```suggestion
You need a **Shared Key** and **Secret Key** in order to access the connector. You also need a **NEP Organization** value.

```

2022-12-05 12:22 UTC, erin-lw commented on pages/connector-authentication/NCRSilver-Authentication.md
> +4.  **NEP Organization** is located under Service User Name. It is the value after "acct:" and before the "@" symbol.
```suggestion
4.  Make note of the **NEP Organization** value under **Service User Name**. This is the value after `acct:` and before the `@` symbol.

```

2022-12-05 12:23 UTC, erin-lw commented on pages/connector-authentication/NCRSilver-Authentication.md
> +    Example: If the Service User Name is acct:test-drive-486bcc60-9426-4e46-bf9c-90l3e6e5883e@44423c74-6324-446b-97d2-e88538c3c926, the **NEP Organization** you need is test-drive-486bcc60-9426-4e46-
```suggestion
    *  For example, if the **Service User Name** is `acct:test-drive-486bcc60-9426-4e46-bf9c-90l3e6e5883e@44423c74-6324-446b-97d2-e88538c3c926`, the **NEP Organization** you need is `test-drive-486bcc60-9426-4e46-bf9c-90l3e6e5883e`.

```

2022-12-05 12:35 UTC, merged