Create 06-counter-storage.md
cyclr/docs pull request #535
Opened 2023-08-24 12:22 UTC by josephclander

2023-09-01 15:26 UTC, joshuamullings requested changes

2023-09-01 15:26 UTC, joshuamullings commented on pages/v2/07-utility-connectors/03-data-storage/06-counter-storage.md
> +To keep multiple counters, scoped globally or to a Cycle, you can use the **Counter Storage** Connector.
```suggestion
 The **Counter Storage** Connector allows for multiple counters, either stored globally or within a Cyclr, to be tracked.
```

2023-09-01 15:26 UTC, joshuamullings commented on pages/v2/07-utility-connectors/03-data-storage/06-counter-storage.md
> +Counters can be created and updated in one part of the Cycle and retrieved in another.
```suggestion
Counters can be created and/or updated in one step of a Cycle and retrieved from another step in a Cycle.
```

2023-09-01 15:26 UTC, joshuamullings commented on pages/v2/07-utility-connectors/03-data-storage/06-counter-storage.md
> +The **Counter Storage** Connector works by using a Name and an Amount. The Name must be unique. The Amount will be 1 by default and can accept float values.
```suggestion
The **Counter Storage** Connector stores and/or adjusts an Amount against a unique Counter Name. The Amount will be adjusted by 1 by default and can accept float values.
```

2023-09-28 17:33 UTC, closed without merging

2023-09-29 08:22 UTC, BenCrum commented
Manually added to Confluence.