Create Epicor.md
cyclr/docs pull request #537
Opened 2023-08-31 14:58 UTC by Tariqk26

Created Connector Partner Guide

2023-09-01 15:18 UTC, joshuamullings requested changes

2023-09-01 15:18 UTC, joshuamullings commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +To authenticate your connector, you need the following information Epicor account.
```suggestion
You need the following information to authenticate the Epicor connector:
```

2023-09-01 15:18 UTC, joshuamullings commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +| Kinetic Server   | The Kinetic Server domain of your Epicor Kinetic account. this will be just domain without any HTTP protocals for example: `ukkineticserver00.epicorsaas.com` |
```suggestion
| Kinetic Server   | The Epicor Kinetic Server account domain and subdomain not including the protocol. For example, if the Epicor Kinetic Server URL is `https://ukkineticserver00.epicorsaas.com` then enter `ukkineticserver00.epicorsaas.com` |
```

2023-09-01 15:18 UTC, joshuamullings commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +| Kinetic Instance | The unique ID for the Instance of the Epicor Kinetic Server you wish to access. for example: `Test001Pilot` |
```suggestion
| Kinetic Instance | The Epicor Kinetic Server unique instance ID. For example, `Test001Pilot`. |
```

2023-09-01 15:18 UTC, joshuamullings commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +| API Key          | The API Key for your Epicor account. To request an API Key you will need to contact [Epicor Support](https://epiccare.epicor.com/epiccare) |
```suggestion
| API Key          | The Epicor Kinetic account API key used to connect to the Epicor Kinetic Instance. To request an API Key, please contact [Epicor Support](https://epiccare.epicor.com/epiccare). |
```

2023-09-01 15:18 UTC, joshuamullings commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +To set up the Epicor connector in Cyclr, go to your Cyclr console:
This section should follow the account setup format I think? It looks like the Epicor connector doesn't have any partner level parameters.

2023-09-01 15:26 UTC, Tariqk26 commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +To set up the Epicor connector in Cyclr, go to your Cyclr console:
Correct, There's no Partner Level Parameters for the Epicor Connector as Each user has their own Server and instance.

2023-09-28 17:38 UTC, BenCrum commented on pages/v2/05-application-connectors/authentication/Epicor.md
> +To set up the Epicor connector in Cyclr, go to your Cyclr console:
In which case, this isn't the correct format. 😊  The 1..8 points here relate to Partner-level parameters, e.g. "Go to "Connectors > Application Connector Library" is at the Partner-level, not at the point you're installing the Connector.

These problems should be resolved when I finish making a "Connector Guide where Partner-level parameters must be set in the Console" template and a "it's all entered when installing a Connector" template for Connector Guides to follow.

Closing this PR as moving into Confluence anyhoo.

2023-09-29 08:21 UTC, closed without merging

2023-09-29 08:21 UTC, BenCrum commented
Manually added to Confluence.